modLoader = "javafml"
loaderVersion = "[46,)"
license = "MIT"

[[mods]]
modId = "drumkit"
version = "${version}"
displayName = "VisorDrumKit"
authors = "Ninix"
displayTest = "NONE"
description = '''
Drum Kit for Visor

'''

[[dependencies.drumkit]]
modId = "visor"
mandatory = true
versionRange = "[0.2.0-alpha,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.drumkit]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.drumkit]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.20.1]"
ordering = "AFTER"
side = "BOTH"